config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  root "static_pages#home"
  #STATICS
  get "/home", to: "static_pages#home"
  get "/about", to: "static_pages#about"
  get '/contact', to: "static_pages#contact"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #SIGN UP
  get 'signup', to: "users#new"
  #LOG IN
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  
  #GET method , request to /products are handled in the index function of the Products Controller
  resources :products
  resources :users
  #'resources' gets all the product urls
  #get "/products", to: "products#index"
  #get "/products/:id", to: "products#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    #attributes are in schema.rb
    validates :name, presence: true, length: { minimum: 3 }
    validates :price, presence: true
    validates :quantity, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.username = username.downcase }
    validates :name,presence: true, length: { minimum: 2, maximum: 50}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :username , presence: true, length: { minimum: 5 ,maximum: 100 },
                format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end
#call it what you want

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    #product_path(product)
    @products = Product.all()
  end

  def show
    #The product is a resource, aka an object of the model
    # @ is a prefix for the variable of this class 'ProductController', this is Perl in disguise
    # in html, with the get path: <a href="<%= product_path(product) %>">
    @product = Product.find(params[:id])
  end
  #get
  def new
    @product = Product.new
  end
  #post
  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to @product
    else
      render :new
    end
  end
  #Both functions must be here, else, the sistem fails
  #one is for getting things ready and validating,
  #the other actually saves the changes
  #get
  def edit
    @product = Product.find(params[:id])
  end
  #patch, put
  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    redirect_to root_path
  end
  
  private
  #This takes the form values
    def product_params
      params.require(:product).permit(:name,:quantity,:price)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "El usuario o contraseña son incorrectos"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = "Bienvenido al Inventario"
      redirect_to @user
    else
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  def show
    begin
      @user = User.find(params[:id])
    rescue
      nil
    end
  end

  private 
    def user_params
      params.require(:user).permit(:name,:username,:password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def full_title(page_title='')
        base_title = "Club Stock"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        reset_session
        @current_user = nil
    end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.username.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end

end

app/views/layouts/_header.html.erb
<header>
	<ul class="header">
        <li><%= link_to "Club Stock", root_path %></li>
       	<li><%= link_to "About", about_path %></li>
       	<li><%= link_to "Contact", contact_path %></li>
        <% if logged_in? %>
	        <li><%= link_to "Yo", current_user %></p></li>
	        <li><%= link_to "Salir", logout_path, method: :delete %></p></li>
        <% else %>
            <li><%= link_to "Comenzar", signup_path %></li>
        <% end %>
    </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: product do |form| %>
    <div class="form-product">
        <div class="form-div">
            <%= form.label :name, 'Nombre' %>
            <%= form.text_field :name %>
            <%= product.errors.full_messages_for(:name).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
        <div class="form-div">
            <%= form.label :quantity, 'Cantidad' %>
            <%= form.number_field :quantity %>
            <%= product.errors.full_messages_for(:quantity).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
        <div class="form-div">
            <%= form.label :price, 'Precio' %>
            <%= form.number_field :price %>
            <%= product.errors.full_messages_for(:price).each do |message| %>
                <div><%= message %></div>
            <% end %>
        </div>
        <div class="form-div">
            <%= form.submit class: 'btn-product' %>
        </div>
    </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editar Producto</h1>

<%= render "form", product: @product %>

app/views/products/index.html.erb
<div class="header-productos">
    <h2>P R O D U C T O S</h2>
</div>

<p class="btn-product"><%= link_to "Nuevo", new_product_path %></p>

<ul>
    <% @products.each do |product| %>
        <li>
            <%= link_to product.name, product %>
        </li>
    <% end %>
</ul>

app/views/products/new.html.erb
<div class="header-productos">
    <h2>NUEVO PRODUCTO</h2>
</div>

<%# The form is now a partial view %>
<%# The file is referred without the underscore
but declared with the underscore at the beginnig %>
<%= render "form", product: @product %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<p>$<%= @product.price %></p>
<p>Cantidad <%= @product.quantity%> </p>

<p><%= link_to "Editar", edit_product_path(@product) %></p>
<p><%= link_to "Eliminar", product_path(@product), method: :delete, data: { confirm: "¿estás seguro?" } %></p>

app/views/static_pages/about.html.erb
<% provide(:title,"About") %>
<h1>SOBRE ESTA PÁGINA</h1>

app/views/static_pages/contact.html.erb
<% provide(:title,"Contact") %>
<h1>Contacto</h1>
<p>En mi :heart: </p>

app/views/static_pages/home.html.erb
<% provide(:title,"Home") %>

<div class="home-background">
    <div class="images">
        <div class="product-1">
        </div>
        <div class="product-2">
        </div>
        <div class="product-3">
        </div>
    </div>
    <div class="title">
        <h1>I N V E N T A R I O</h1>
    </div>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
    <% @users.each do |user| %>
        <li>
            <%= link_to user.name, user %>
        </li>
    <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Registro') %>

<div class="register-container">
  <div class="register-name">
    <h1>Regístrate</h1>
    <p>Sé un usuario para un mejor manejo de tu Inventario</p>
  </div>
  <div class="register-form">
    <%= form_with(model: @user, local: true) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-item">
        <%= f.text_field :name, class:"form-item-field", placeholder: "Nombre Completo" %>
      </div>
      <div class="form-item">
        <%= f.text_field :username, class:"form-item-field",placeholder: "Correo Electrónico" %>
      </div>
      <div class="form-item">
        <%= f.password_field :password, class:"form-item-field",placeholder: "Contraseña" %>
      </div>
      <div class="form-item">
        <%= f.password_field :password_confirmation, class:"form-item-field",placeholder: "Confirma tu contraseña" %>
      </div>
      <div class="form-item">
        <%= f.submit "Crea tu cuenta", class: "btn-submit" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% if @user %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= gravatar_for @user %>
    <p><%= @user.name %> - <%= @user.username %></p>
<% else %>
    <p>No existe este usuario</p>
<% end %>